; PlatformIO Project Configuration File for ESP32 Device Manager
; Climate Pro - OS (Stage Climatisation MLCT)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Configuration du port COM (Detecte sur CH340)
upload_port = COM5
monitor_port = COM5

; Configuration du moniteur serie
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
upload_speed = 115200

; Systeme de fichiers LittleFS & Partitionnement 4MB (2MB App / 2MB LittleFS)
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; Dependances requises
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    mathieucarbou/AsyncTCP @ ^3.2.4
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

; Options de compilation C++17
build_flags = 
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=0

